### ISSUE TITLE
Linux server daemon will enter an infinite-loop, due to polling on stdin for 'q'

### ISSUE THREAD

**Issue by sp193** [eProsima/Micro-XRCE-DDS-Agent#100]
Hi all,

I am involved in a project that involves setting up XRCE Agent as a Linux server daemon. Unfortunately, the present version will poll stdin for 'q', which will fail when XRCE Agent runs as a Linux daemon, leaving XRCE Agent printing a never-ending series of "Press 'q' for exit". This happens because stdin is routed to /dev/null by default, when the software is run as a daemon.

I currently have a patch that will change the polling for 'q' to a check for the SIGTERM signal instead, for only the Linux server. SIGTERM is generated when the software is terminated, like when the service is stopped with kill or if the user presses CTRL+C.

I wrote the patch for an earlier version of XRCE-DDS-Agent, before the platform-specific code was moved from microxrce_agent.cpp into other classes. So I will have to update it first. But before I upgrade the patch and make a pull request, I would like to ask if this is the preferred way and if this patch is wanted.

Thanks for your attention!

**Comment by BorjaOuterelo** [comment]
Hi @sp193.

If you already have a solution for this, a pull request will be very welcome.
Thanks in advance.
