### ISSUE TITLE
MTU configuration in V1.1.0 [6198]

### ISSUE THREAD

**Issue by glchua2** [eProsima/Micro-XRCE-DDS-Agent#108]
Previously in XRCE Agent V1.0.3, CONFIG_TCP_TRANSPORT_MTU configuration parameters can be set at compile time. However, after updating to V1.1.0, this configuration options is no longer available to set during compile time.

How can we change this value now?

**Comment by julianbermudez** [comment]
Hi @glchua2,

The `CONFIG_TCP_TRANSPORT_MTU` set the buffer size in the previous version. Now it is set to the maximum message size of the DDS-XRCE protocol, thus 64KB. Nevertheless, you can change it manually in server's `buffer_` member variable.

**Comment by glchua2** [comment]
@julianbermudez Thanks for the clarification.
