### ISSUE TITLE
large message(Error written data on DDS entity) 

### ISSUE THREAD

**Issue by baozeng90** [eProsima/Micro-XRCE-DDS-Agent#136]
1.my message is about 2500, I modified the file client.config(CONFIG_UDP_TRANSPORT_MTU=4096).
2.but it not work  ------ Error written data on DDS entity
3.Is there anything else that needs to be changed

**Comment by julianbermudez** [comment]
Hi @baozeng90,

Your issue could be related to #4. So, you should fix the issue changing the `<historyMemoryPolicy>` in _agent.refs_.
