### ISSUE TITLE
Binaries not found due to UAGENT_ISOLATED_INSTALL

### ISSUE THREAD

**Issue by karl-schulz** [eProsima/Micro-XRCE-DDS-Agent#166]
Hi!
After building and installing the MicroXRCEAgent using the official [tutorial](https://micro-xrce-dds.docs.eprosima.com/en/latest/installation.html#installing-the-agent-stand-alone), the binaries are not found when executing `MicroXRCEAgent`.

[This Guide](https://micro-xrce-dds.docs.eprosima.com/en/latest/quickstart.html) also assumes the binaries are located in `/usr/local/bin`. They are actually in `/usr/local/microxrcedds_agent-1.3.0/bin`.

Correct me if I'm wrong, but defaulting `UAGENT_ISOLATED_INSTALL` to `ON` breaks the tutorial in this form. Was it added for development purposes and left on ON by accident? Or is this on purpose?

System: NVIDIA Jetson TX2 (Ubuntu-like L4T)
Reproduction: Following the tutorial.

Thanks!

**Comment by pablogs9** [comment]
Hello @karl-schulz , thanks for the issue.

It has been addressed here https://github.com/eProsima/Micro-XRCE-DDS-Agent/pull/167 and here https://github.com/eProsima/Micro-XRCE-DDS-Client/pull/157

I'll close this issue when merged.

**Comment by karl-schulz** [comment]
Cool, thanks for the fast reply!

**Comment by pablogs9** [comment]
Fixes merged, closing
