### ISSUE TITLE
HELP    Performing configure step for 'foonathan_memory'

### ISSUE THREAD

**Issue by fenghui336** [eProsima/Micro-XRCE-DDS-Agent#220]
loading initial cache file /home/fenghui/Micro-XRCE-DDS-Agent/build/foonathan_memory/tmp/foonathan_memory-cache-.cmake
-- Checking 13 features
CMake Error at cmake/comp/comp_base.cmake:288 (message):
  error downloading feature file cpp11_lang/alignof.cmake: "Couldn't connect
  to server".  Check spelling of feature.

    Trying 0.0.0.0...

  TCP_NODELAY set

  connect to 0.0.0.0 port 443 failed: Connection refused

    Trying ::...

  TCP_NODELAY set

  connect to :: port 443 failed: Connection refused

  Failed to connect to raw.githubusercontent.com port 443: Connection refused

  Closing connection 0

Call Stack (most recent call first):
  cmake/comp/comp_base.cmake:347 (_comp_fetch_feature)
  cmake/comp/comp_base.cmake:369 (_comp_handle_feature)
  cmake/compatibility.cmake:13 (comp_target_features)
  CMakeLists.txt:50 (include)

-- Configuring incomplete, errors occurred!
See also "/home/fenghui/Micro-XRCE-DDS-Agent/build/foonathan_memory/src/foonathan_memory-build/CMakeFiles/CMakeOutput.log".
CMakeFiles/foonathan_memory.dir/build.make:105: recipe for target 'foonathan_memory/src/foonathan_memory-stamp/foonathan_memory-configure' failed
make[2]: *** [foonathan_memory/src/foonathan_memory-stamp/foonathan_memory-configure] Error 1
CMakeFiles/Makefile2:295: recipe for target 'CMakeFiles/foonathan_memory.dir/all' failed
make[1]: *** [CMakeFiles/foonathan_memory.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by pablogs9** [comment]
I think that `Failed to connect to raw.githubusercontent.com port 443: Connection refused` is related to your internet connection. We have had no problem building the Micro-XRCE Agent, is possible for you to retry with another computer and/or in another network?
