### ISSUE TITLE
FAST-DDS and Micro-XRCE-DDS-Agnet

### ISSUE THREAD

**Issue by fenghui336** [eProsima/Micro-XRCE-DDS-Agent#221]
[ 44%] Performing download step (git clone) for 'fastdds'
Cloning into 'fastdds'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

When I install micro-DDS-agent, I always can't download fast-dds by executing make command, but I can download it by using git clone command directly. Now I want to download fast-dds and put it in the corresponding folder of micro-DDS-agent. Where should the files in fast-dds be put in micro DDS agent?

**Comment by pablogs9** [comment]
These curl problems seem to be related to your network.
Here you can see the build procedure for the Micro XRCE-DDS Agent:

https://asciinema.org/a/xmh8b4clNifxEUkw4y7q6oZoq

Closing since not related.
