### ISSUE TITLE
get_transport_interfaces : segment fault if ifa_addr is NULL

### ISSUE THREAD

**Issue by DenvE** [eProsima/Micro-XRCE-DDS-Agent#258]
## Issue template

- PC: 
- archlinux : 
- default flags : cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
- V2.0.0

#### Steps to reproduce the issue
start agent : MicroXRCEAgent udp4 -p 2032 -m ced  -d --p2p 2033

just build with cmake and ninja for pc.

#### Expected behavior
should not crash
#### Actual behavior
access of NULL pointer, agent stops
#### Additional information
pc has vpn0 which doesn't seems to have ifa_addr.

![image](https://user-images.githubusercontent.com/38785595/124147620-26bc8680-da8f-11eb-9921-531a4bf3c261.png)

solution: check

**Comment by Acuadros95** [comment]
This was solved here: https://github.com/eProsima/Micro-XRCE-DDS-Agent/pull/285

detail:
https://github.com/eProsima/Micro-XRCE-DDS-Agent/blob/91986fad5a0fd3191e5167eccdc75ae6441e6b9c/include/uxr/agent/transport/util/InterfaceLinux.hpp#L51
