### ISSUE TITLE
Agent's DataWriter write might be blocked sometimes.

### ISSUE THREAD

**Issue by liyue75** [eProsima/Micro-XRCE-DDS-Agent#271]
I use Micro-XRCE-DDS to get data from embeding system.
My MicroDDS client is running on stm32, MicroDDS Agent and DDS subscriber is running on nonopi.
I use `-v 5 ` to show more debug message, 
and I found sometimes the agent has received message, but when it call `write` in `DataWriter.cpp`, the function will block for several seconds, so in this period, there are just data in from stm32, but no data out to DDS subscriber, which I mean
the `receive loop` is still running, but the `processing_loop` is blocked. 
After the `write` function is unblocked and return, the data received and stored in `input_scheduler_` can be sent. 
 
The Agent's middleware is FastDDS v2.0.2,  my DDS subscriber's version is 2.3.0.
The Agent and DDS subscriber all use `builtin transport` (I find that they will automatically  use **UDPv4** and localhost, Maybe their versions are different so they do not use **SHM**).
What might be causing write to block? Does it have anything to do with my nanopi's localhost?

**Comment by liyue75** [comment]
I found that the problem was most likely caused by DataWriter's QOS.
Although I set the DataWriter's reliability to **BEST_EFFORT**,  but the qos of the DataWriter actually created by the agent is **RELIABLE**.

**Comment by pablogs9** [comment]
Which version of the Micro XRCE-DDS Agent are you using?

How are you creating the entities in the Micro XRCE-DDS Client? Can you share the code?

**Comment by liyue75** [comment]
@pablogs9 
Sorry, I'm not very sure. I can not reproduce the issue now. 
I'm going to close this issue, if I get it again later I will reopen this issue.
