### ISSUE TITLE
Is it possible to run agents on Android  

### ISSUE THREAD

**Issue by lxc777** [eProsima/Micro-XRCE-DDS-Agent#305]
Can you give an example 
Thank you very much!

**Comment by pablogs9** [comment]
Hi @lxc777, [@kneep](https://github.com/kneep) make some related contributions (https://github.com/eProsima/Micro-XRCE-DDS-Agent/pull/280, https://github.com/eProsima/Micro-XRCE-DDS-Agent/pull/282, https://github.com/eProsima/Micro-XRCE-DDS-Agent/pull/283) so I guess that is possible to run the Micro XRCE-DDS in Android but it is not officially supported so we do not have examples or tutorials.
