### ISSUE TITLE
Multiple agents

### ISSUE THREAD

**Issue by lxc777** [eProsima/Micro-XRCE-DDS-Agent#309]
Hi，When there are multiple agents and each agent has only different IP, how to distinguish the connection in the network of ros2. What parameters or settings should the agent add or change the settings of ros2?

**Comment by pablogs9** [comment]
Could you explain better the issue?

**Comment by lxc777** [comment]
Sorry, maybe I didn't make it clear.
Problems encountered: I have multiple micro xrce DDS agents in the same network segment. They communicate with ros2 and encounter problems when sending and listening to ros2. When ros2 publishes a message, micro xrce DDS starts subscription, and multiple agents will receive messages at this time. Is there any way to specify a specific proxy subscription?

**Comment by pablogs9** [comment]
Well, DDS uses the publication/subscription paradigm where the data produced by one publisher will reach all the subscribers that match the publisher.

I'm not sure if I have understood well your question. Could you expose a use case and a demo where we can reproduce your problem?

**Comment by lxc777** [comment]
Yes, DDS network, sharing publishers and subscribers. Now I need to limit this sharing. I want to use ros2 for specific users

Micro xrce DDS agent node, publish and subscribe, and other nodes are not affected.

**Comment by lxc777** [comment]
What I learned can be achieved through ROS_ DOMAIN_ ID is restricted. How can I find the registered ROS_ DOMAIN_ ID to avoid duplication. 
PC1  open micro xrce DDS agent：
![1649727957](https://user-images.githubusercontent.com/49939922/162866573-dd21dc31-f0d3-444b-98a1-d50bfc37b6fa.jpg)

PC1   open ros2-android：
![Screenshot_20220412_094941](https://user-images.githubusercontent.com/49939922/162866743-4b385580-b518-4350-8101-1c8a5d4654b0.png)

PC2  open  micro xrce DDS  PublishHelloWorld：
![1649728088](https://user-images.githubusercontent.com/49939922/162866921-c4d0d405-9d0f-4cd6-86b2-813afa44967a.jpg)

PC2 Vm ubuntu20.04  open publication and subscription ：
![7d01ec80d284474a1e7f35ea2d41af4](https://user-images.githubusercontent.com/49939922/162867083-d028824f-6aa3-4e8c-b3f4-a13e0d696e86.png)

**Comment by pablogs9** [comment]
On the ROS 2 side, as you can see in the [documentation](https://docs.ros.org/en/foxy/Concepts/About-Domain-ID.html), the domain id can be configured by setting the environment variable `DOMAIN_ID` to de desired value. In XRCE-DDS, as stated in the [documentation](https://micro-xrce-dds.docs.eprosima.com/en/stable/client_api.html#create-entities-by-xml), each participant creatin API has a `domain` argumento for setting this value.

I'm closing, please reopen if you have further questions.

**Comment by lxc777** [comment]
Thank you. It's very useful to me
