### ISSUE TITLE
Some error related to git submodule

### ISSUE THREAD

**Issue by binbowang1987** [eProsima/Micro-XRCE-DDS-Agent#343]
## Issue template

- Hardware description: 
- OS: 
- Installation type: 
- Version or commit hash: 

I want to push code to my custom repo, but failed. 
![image](https://github.com/eProsima/Micro-XRCE-DDS-Agent/assets/8586061/ecfca37a-0746-4b44-b2d6-8e324e7f4ae5)

#### Steps to reproduce the issue

git clone https://github.com/eProsima/Micro-XRCE-DDS-Agent.git
git remote add ks-origin git@172.26.193.34:dds/micro-xrce-dds-agent.git
git push ks-origin master

#### Expected behavior
git push success.

**Comment by pablogs9** [comment]
This error is related to your git procedures not to Micro XRCE-DDS. Closing as not related.
