### ISSUE TITLE
MicroXRCEAgent: error while loading shared libraries: libmicroxrcedds_agent.so.2.4

### ISSUE THREAD

**Issue by sastel** [eProsima/Micro-XRCE-DDS-Agent#352]
## After Installation, MicroXRCEAgent Can't Find Dynamically Linked Library

- Hardware description: Dell Laptop
- OS: Ubuntu 22.04 LTS on Windows Subsystem for Linux (WSL)
- Installation type: [As per Quick Start Instructions](https://micro-xrce-dds.docs.eprosima.com/en/latest/quickstart.html#running-an-agent)
- Version or commit hash: v2.4.1

#### Steps to reproduce and fix the issue
```
sstel@5JRJ4Y3:/usr/local/bin
$ MicroXRCEAgent udp4 -p 2019
MicroXRCEAgent: error while loading shared libraries: libmicroxrcedds_agent.so.2.4: cannot open shared object file: No such file or directory

sstel@5JRJ4Y3:/usr/local/bin
$ whereis libmicroxrcedds_agent.so.2.4
libmicroxrcedds_agent.so.2.4: /usr/local/lib/libmicroxrcedds_agent.so.2.4

sstel@5JRJ4Y3:/usr/local/bin
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

sstel@5JRJ4Y3:/usr/local/bin
$ MicroXRCEAgent udp4 -p 2019
[1698840799.551829] info     | UDPv4AgentLinux.cpp | init                     | running...             | port: 2019
[1698840799.552641] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 4

sstel@5JRJ4Y3:/usr/local/bin
$ export LD_LIBRARY_PATH=

sstel@5JRJ4Y3:/usr/local/bin
$ sudo ldconfig
/sbin/ldconfig.real: /usr/lib/wsl/lib/libcuda.so.1 is not a symbolic link

sstel@5JRJ4Y3:/usr/local/bin
$ MicroXRCEAgent udp4 -p 2019
[1698840947.631476] info     | UDPv4AgentLinux.cpp | init                     | running...             | port: 2019
[1698840947.632115] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 4
```

Not sure how you would like to handle this, but it might be worth adding some notes on updating the dynamic linker to the documentation. It tripped me up at first.

**Comment by pablogs9** [comment]
Check 
![image](https://github.com/eProsima/Micro-XRCE-DDS-Agent/assets/7647884/bd8542e0-bc21-407c-8f90-85202a9b7eac)

Here: https://micro-xrce-dds.docs.eprosima.com/en/latest/installation.html#installing-the-agent-standalone

**Comment by sastel** [comment]
Wow I totally missed that. Thanks @pablogs9!
