### ISSUE TITLE
Cross Endian between XRCE-DDS Agent and XRCE-DDS Client

### ISSUE THREAD

**Issue by kimsos0723** [eProsima/Micro-XRCE-DDS-Agent#355]
hi, I try to porting on PowerPC t2080rdb the XRCE-Client
I configured the Client to Big-endian and running `SubscribeHelloWorld` on ppc
 So result like-below 
<img width="890" alt="image" src="https://github.com/eProsima/Micro-XRCE-DDS-Agent/assets/36767927/1583eeb0-ec10-45f4-bb4c-9caa0d1ab8fd">

but the Agent read  Xtype String length as Little-endian, even if submessage Header flag is 0x04

Did I do something wrong?

**Comment by pablogs9** [comment]
Could you share a replicator?

**Comment by kimsos0723** [comment]
I can't understand what replicator means.
but I just changed the Client's  and CDR's CMakeList `CONFIG_BIG_ENDIANNESS` options on

**Comment by pablogs9** [comment]
Is correctly set the endianness flag on the ucdrBuffer structure:

void on_topic(
        uxrSession* session,
        uxrObjectId object_id,
        uint16_t request_id,
        uxrStreamId stream_id,
        struct ucdrBuffer* ub,
        uint16_t length,
        void* args)
{
    // Check this
    printf("ENDIANESS: %d\n", ub->endianness);

    (void) session; (void) object_id; (void) request_id; (void) stream_id; (void) length;

    HelloWorld topic;
    HelloWorld_deserialize_topic(ub, &topic);

    printf("Received topic: %s, id: %i\n", topic.message, topic.index);

    uint32_t* count_ptr = (uint32_t*) args;
    (*count_ptr)++;
}

**Comment by kimsos0723** [comment]
Here's what the client sees as the received message
<img width="528" alt="image" src="https://github.com/eProsima/Micro-XRCE-DDS-Agent/assets/36767927/38e22388-d6f0-450f-b4df-a14469f8408b">

**Comment by kimsos0723** [comment]
The length of a string of type Xtype seems to be misread as a little-endian in the agent.

**Comment by pablogs9** [comment]
> Here's what the client sees as the received message <img alt="image" width="528" src="https://user-images.githubusercontent.com/36767927/284440660-38e22388-d6f0-450f-b4df-a14469f8408b.png">

Sorry, but I cannot retrieve enough information from this

**Comment by kimsos0723** [comment]
Oh something changed, When I built the agent in the develop bench 
But previous error condition has passed but raised seg fault in Agent
<img width="1190" alt="image" src="https://github.com/eProsima/Micro-XRCE-DDS-Agent/assets/36767927/a92cf315-82db-42a6-bd60-8eba614d4b53">
