### ISSUE TITLE
Multiple Agent

### ISSUE THREAD

**Issue by OpusK** [eProsima/Micro-XRCE-DDS-Agent#41]
Hi,

 - Micro-XRCE-DDS Agent 1.0.1 (feature/serialdebug)
 - Micro-XRCE-Client 1.0.1
 - ROS2 Crystal

When I try to run the agent using serial first and then udp, the following error occurs.

![111](https://user-images.githubusercontent.com/18085958/50205504-ccb1b500-03ab-11e9-90b9-0db36de64ceb.jpg)

It simply says ERROR.
Conversely, if I run udp first and then serial, I can run both, but no Topic will be generated.

**Comment by julianbermudez** [comment]
Hi @OpusK, 

I fixed this issue in feature/serialdebug. The problem was that Fast RTPS made use of the port 7400, and this is the discovery port established by the XRCE. Now both Agent and Fast RTPS can shared this port. I hope it helps you!

**Comment by OpusK** [comment]
Hi, @julianbermudez 

Thanks for your support!
Resolved!
