### ISSUE TITLE
Serial baudrate that can be set by the user.

### ISSUE THREAD

**Issue by OpusK** [eProsima/Micro-XRCE-DDS-Agent#43]
Hi, 

Currently, the Agent is fixed to set Serial to 115200 baud rate.
There is no problem with USB, but in case of UART, baud rate is not correct.

Can you add the baud rate parameter to the CLI?

eg.
```
$ MicroXRCEAgent serial /dev/ttyACM0 115200 
```

**Comment by BorjaOuterelo** [comment]
Hi @OpusK 

Thanks for pointing out this enhancement.
We will take into account it and add it in the next revision of the CLI.

Thanks.

**Comment by lemunozm** [comment]
Hi @OpusK,

the feature that allows setting the baud rate is already merged in master,

**Comment by OpusK** [comment]
Hi, @lemunozm, thank you for your support!

I have already tested this feature :) Thank you.
