### ISSUE TITLE
 Can't reconnect Micro XRCE-DDS serial client using the same serial device and different client keys

### ISSUE THREAD

**Issue by qeyup** [eProsima/Micro-XRCE-DDS-Agent#48]
Error occurs when executing the below steps

**step 1** Run Micro XRCE-DDS  Agent using pseudo-serial device and leave it opened

```bash
./MicroXRCEAgent pseudo-serial
```

**step 2** Run  Micro XRCE-DDS client shape demo, create a session and close execution.

```bash
./ShapeDemoClient --serial /dev/pts/AGENT_RETUNED_DEVICE --key 1
create_session
```

The creation is a success.

**step 3** Run again Micro XRCE-DDS client shape demo using the same pseudo-serial device (/dev/pts/AGENT_RETUNED_DEVICE) but different client key.

```bash
./ShapeDemoClient --serial /dev/pts/AGENT_RETUNED_DEVICE --key 2
create_session
```

In the execution, the creation is unsuccessful.

> **Micro XRCE-DDS Agent branch:** master
> **Micro XRCE-DDS Client branch:** master

**Comment by lemunozm** [comment]
This bug is already fixed in develop (commit https://github.com/eProsima/Micro-XRCE-DDS-Agent/commit/283a7eabf4a3ec2eb70ad100722a912d278d4cd7). It will be merge to master with the next release.
