### ISSUE TITLE
Documentation of message envelope for serial transport

### ISSUE THREAD

**Issue by christianrauch** [eProsima/Micro-XRCE-DDS-Agent#64]
Is there a formal documentation about the message envelop used for the serial transport?

The DDS-XRCE (version 1.0 beta) only specifies the XRCE protocol without additional message envelops for the serial protocol. In section 11.4 it is therefore stated that this will be part of future revisions:
> [...] in order to get transparent interoperability between vendors it is required to define the precise encoding of the transport locators as well as the means to discover agents and establish initial communicators. Therefore it is expected that future revisions of this specification will provide additional transport mappings.

By examining the `uxr_write_serial_msg` function, it is possible to reconstruct the header:
https://github.com/eProsima/Micro-XRCE-DDS-Agent/blob/a495c65faa964ddc068ac6e1249f17f5c9f92787/src/cpp/transport/serial/serial_protocol.c#L127-L131
and footer:
https://github.com/eProsima/Micro-XRCE-DDS-Agent/blob/a495c65faa964ddc068ac6e1249f17f5c9f92787/src/cpp/transport/serial/serial_protocol.c#L161-L187

Is there a formal definition of the serial header and footer for XRCE messages?

**Comment by julianbermudez** [comment]
Hi @christianrauch,

We made a formal request based on [this issue](https://issues.omg.org/issues/spec/DDS-XRCE/1.0b1#issue-44481) to the DDS-XRCE standard in order to standardize the mapping to Serial Transport. We hope it will be accepted for the new revision of the standard.
