### ISSUE TITLE
the Performance of Sub/Pub Topics [5045]

### ISSUE THREAD

**Issue by baozeng90** [eProsima/Micro-XRCE-DDS-Agent#67]
1、when I pub topics(maybe 250 bytes,100Hz.Sub client  can not receive all the topics.

2、Is there has some parameters (possible performance improvements )?

**Comment by julianbermudez** [comment]
Hi @baozeng90,

You have several ways to improve the reliability in Micro XRCE-DDS.

The first one is to use reliable streams for communication. You can take a look at the Client [Subscriber](https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/master/examples/SubscribeHelloWorld/main.c) and [Publisher](https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/master/examples/PublishHelloWorld/main.c) example.

The second one is related to Fast RTPS (the DDS middleware used by the Agent).
It defines different [QoS](https://fast-rtps.docs.eprosima.com/en/latest/xmlprofiles.html#qos), in particular, I will use the `historyQos`, for example:

```
<data_reader ...>
    <topic>
        <historyQos>
            <kind>KEEP_LAST</kind>
            <depth>20</depth>
        </historyQos>
    </topic>
</data_reader>
```

Take into account that the `<data_reader>` and `<publisher>` profiles are equivalent, as well as, the `<data_writer>` and `<subscriber>`.

I hope it helps you.
