### ISSUE TITLE
standard DDS QoS support [5283]

### ISSUE THREAD

**Issue by jerry2714** [eProsima/Micro-XRCE-DDS-Agent#76]
Hi, I'm trying to set QoS `writer_data_lifecycle` to datawriter, but there seems no API to do this in Client. Then I found that maybe I can write the XML file and assign it to Agent, but the XML configuration syntax is follow the same rule as **Fast RTPS**. I wonder is there any ways to set standard DDS QoS to DDS objects?

**Comment by julianbermudez** [comment]
Hi @jerry2714,

Currently, we only have support for XML syntax of Fast RTPS, and it has no support for `lifecycle`.
If you are interested in this feature we can give you support, but it is something we should carefully discuss.
