### ISSUE TITLE
When is the version release for FastRTPS 1.8.0 for the ROS2 Dashing version?

### ISSUE THREAD

**Issue by OpusK** [eProsima/Micro-XRCE-DDS-Agent#80]
Hi,

The ROS2 Dashing version will be released on May 31st.
Last week I saw FastRTPS 1.8.0 applied to the ROS2 master version. When will XRCE-Agent, which can cope with this 1.8.0 version, be released?

**Comment by BorjaOuterelo** [comment]
Hi @OpusK 

This is work in progress, so expect it to be released soon. The plan is to have a new Micro XRCE-DDS version (Client and Agent) during the first weeks of the next month.
