### ISSUE TITLE
TB3-Ros2 no response after Ubuntu 18.04.2 upgrade to latest patch.

### ISSUE THREAD

**Issue by rafaelhuang-intel** [eProsima/Micro-XRCE-DDS-Agent#93]
ISSUE TEMPLATE ver. 0.2.0

Which TurtleBot3 you have?

Waffle & Waffle Pi
Which SBC(Single Board Computer) is working on TurtleBot3?

Intel NUC (I7-6700)
Which OS you installed in SBC?

Ubuntu 18.04 LTS (Bionic Beaver)
Below is execution steps:

install Ubuntu 18.04.2 LTS (Bionic Beaver) (kernal 4.15.x or 4.18.x)
sudo apt update
sudo apt upgrade
after all ubuntu patch updated, install all TB3 relate package, like TB3, Navigation2, Cartographer, etc.
run TB3 and Cartographer SLAM (or navigation)
All data show on terminal:

intel@intel-desktop:~/turtlebot3$ cd ~/turtlebot3 && MicroXRCEAgent serial /dev/ttyACM0
Serial agent initialization... OK
Enter 'q' for exit

cd ~/turtlebot3 && MicroXRCEAgent udp 2018
UDP agent initialization... OK
Enter 'q' for exit
RTPS Participant matched 1.f.59.93.f4.43.0.0.1.0.0.0|0.0.1.c1
RTPS Participant matched 1.f.59.93.fe.43.0.0.1.0.0.0|0.0.1.c1
RTPS Participant matched 1.f.59.93.fd.43.0.0.1.0.0.0|0.0.1.c1
RTPS Subscriber matched 1.f.59.93.fe.43.0.0.1.0.0.0|0.0.22.4
RTPS Participant matched 1.f.59.93.b.44.0.0.1.0.0.0|0.0.1.c1
RTPS Participant matched 1.f.59.93.15.44.0.0.1.0.0.0|0.0.1.c1
RTPS Participant matched 1.f.59.93.14.44.0.0.1.0.0.0|0.0.1.c1
RTPS Participant matched 1.f.59.93.14.44.0.0.2.0.0.0|0.0.1.c1
RTPS Participant matched 1.f.59.93.16.44.0.0.1.0.0.0|0.0.1.c1
RTPS Participant unmatched 1.f.59.93.15.44.0.0.1.0.0.0|0.0.1.c1
RTPS Participant unmatched 1.f.59.93.b.44.0.0.1.0.0.0|0.0.1.c1
RTPS Participant unmatched 1.f.59.93.14.44.0.0.2.0.0.0|0.0.1.c1
RTPS Participant unmatched 1.f.59.93.14.44.0.0.1.0.0.0|0.0.1.c1
RTPS Subscriber unmatched 1.f.59.93.fe.43.0.0.1.0.0.0|0.0.22.4
RTPS Participant unmatched 1.f.59.93.fd.43.0.0.1.0.0.0|0.0.1.c1
RTPS Participant unmatched 1.f.59.93.fe.43.0.0.1.0.0.0|0.0.1.c1
RTPS Participant unmatched 1.f.59.93.f4.43.0.0.1.0.0.0|0.0.1.c1

intel@intel-desktop:~$ ~/turtlebot3/turtlebot3_lidar
turtlebot3 lidar client setup complete!
1 - Sent topic: 2.101000, range_max: 361
2 - Sent topic: 2.127000, range_max: 361
3 - Sent topic: 2.128000, range_max: 361
4 - Sent topic: 2.114000, range_max: 361
5 - Sent topic: 2.128000, range_max: 361
6 - Sent topic: 2.144000, range_max: 361
7 - Sent topic: 2.133000, range_max: 361
8 - Sent topic: 2.121000, range_max: 361
9 - Sent topic: 2.133000, range_max: 361
10 - Sent topic: 2.102000, range_max: 361
11 - Sent topic: 2.129000, range_max: 361
12 - Sent topic: 2.091000, range_max: 361
13 - Sent topic: 2.100000, range_max: 355
14 - Sent topic: 2.140000, range_max: 361
15 - Sent topic: 2.116000, range_max: 361
16 - Sent topic: 2.115000, range_max: 361
17 - Sent topic: 2.128000, range_max: 361
18 - Sent topic: 2.123000, range_max: 361
19 - Sent topic: 2.134000, range_max: 361
20 - Sent topic: 2.125000, range_max: 361
21 - Sent topic: 2.123000, range_max: 361
22 - Sent topic: 2.128000, range_max: 361
23 - Sent topic: 2.108000, range_max: 361
24 - Sent topic: 2.122000, range_max: 361
25 - Sent topic: 2.131000, range_max: 361
26 - Sent topic: 2.113000, range_max: 361
27 - Sent topic: 2.123000, range_max: 361
28 - Sent topic: 2.121000, range_max: 361
29 - Sent topic: 2.135000, range_max: 361
30 - Sent topic: 2.114000, range_max: 361
31 - Sent topic: 2.115000, range_max: 361
32 - Sent topic: 2.143000, range_max: 361
33 - Sent topic: 2.115000, range_max: 361
34 - Sent topic: 2.117000, range_max: 361
35 - Sent topic: 2.149000, range_max: 361
36 - Sent topic: 2.114000, range_max: 361
37 - Sent topic: 2.131000, range_max: 361
38 - Sent topic: 2.131000, range_max: 361
39 - Sent topic: 2.133000, range_max: 361
40 - Sent topic: 2.122000, range_max: 361

intel@intel-desktop:~$ ros2 launch turtlebot3_bringup robot.launch.py
[INFO] [launch]: All log files can be found below /home/intel/.ros/log/2019-05-27-01-26-36-848251-intel-desktop-17396
[INFO] [launch]: Default logging verbosity is set to INFO
urdf_file_name : turtlebot3_waffle.urdf
[INFO] [robot_state_publisher-1]: process started with pid [17405]
[INFO] [turtlebot3_ros-2]: process started with pid [17406]
[robot_state_publisher-1] Initialize urdf model from file: /opt/robot_sdk/device/turtlebot3_description/share/turtlebot3_description/urdf/turtlebot3_waffle.urdf
[robot_state_publisher-1] Parsing robot urdf xml string.
[robot_state_publisher-1] Link base_link had 7 children
[robot_state_publisher-1] Link camera_link had 2 children
[robot_state_publisher-1] Link camera_depth_frame had 1 children
[robot_state_publisher-1] Link camera_depth_optical_frame had 0 children
[robot_state_publisher-1] Link camera_rgb_frame had 1 children
[robot_state_publisher-1] Link camera_rgb_optical_frame had 0 children
[robot_state_publisher-1] Link caster_back_left_link had 0 children
[robot_state_publisher-1] Link caster_back_right_link had 0 children
[robot_state_publisher-1] Link imu_link had 0 children
[robot_state_publisher-1] Link base_scan had 0 children
[robot_state_publisher-1] Link wheel_left_link had 0 children
[robot_state_publisher-1] Link wheel_right_link had 0 children
[robot_state_publisher-1] got segment base_footprint
[robot_state_publisher-1] got segment base_link
[robot_state_publisher-1] got segment base_scan
[robot_state_publisher-1] got segment camera_depth_frame
[robot_state_publisher-1] got segment camera_depth_optical_frame
[robot_state_publisher-1] got segment camera_link
[robot_state_publisher-1] got segment camera_rgb_frame
[robot_state_publisher-1] got segment camera_rgb_optical_frame
[robot_state_publisher-1] got segment caster_back_left_link
[robot_state_publisher-1] got segment caster_back_right_link
[robot_state_publisher-1] got segment imu_link
[robot_state_publisher-1] got segment wheel_left_link
[robot_state_publisher-1] got segment wheel_right_link
[turtlebot3_ros-2] [INFO] [turtlebot3_node]: Init TurtleBot3 Node Main
[robot_state_publisher-1] Adding fixed segment from base_footprint to base_link
[robot_state_publisher-1] Adding fixed segment from base_link to camera_link
[robot_state_publisher-1] Adding fixed segment from camera_link to camera_depth_frame
[robot_state_publisher-1] Adding fixed segment from camera_depth_frame to camera_depth_optical_frame
[robot_state_publisher-1] Adding fixed segment from camera_link to camera_rgb_frame
[robot_state_publisher-1] Adding fixed segment from camera_rgb_frame to camera_rgb_optical_frame
[robot_state_publisher-1] Adding fixed segment from base_link to caster_back_left_link
[robot_state_publisher-1] Adding fixed segment from base_link to caster_back_right_link
[robot_state_publisher-1] Adding fixed segment from base_link to imu_link
[robot_state_publisher-1] Adding fixed segment from base_link to base_scan
[robot_state_publisher-1] Adding moving segment from base_link to wheel_left_link
[robot_state_publisher-1] Adding moving segment from base_link to wheel_right_link

intel@intel-desktop:~$ ros2 launch turtlebot3_cartographer cartographer.launch.py
[INFO] [launch]: All log files can be found below /home/intel/.ros/log/2019-05-27-01-26-39-625237-intel-desktop-17419
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [cartographer_node-1]: process started with pid [17428]
[INFO] [occupancy_grid_node-2]: process started with pid [17429]
[INFO] [rviz2-3]: process started with pid [17430]
[cartographer_node-1] I0527 01:26:40.000000 17428 configuration_file_resolver.cc:41] Found '/opt/robot_sdk/device/turtlebot3_cartographer/share/turtlebot3_cartographer/config/turtlebot3_lds_2d.lua' for 'turtlebot3_lds_2d.lua'.
[cartographer_node-1] I0527 01:26:40.000000 17428 configuration_file_resolver.cc:41] Found '/home/intel/robot_sdk/sdk_ws/device_ws/install/cartographer/share/cartographer/configuration_files/map_builder.lua' for 'map_builder.lua'.
[cartographer_node-1] I0527 01:26:40.000000 17428 configuration_file_resolver.cc:41] Found '/home/intel/robot_sdk/sdk_ws/device_ws/install/cartographer/share/cartographer/configuration_files/map_builder.lua' for 'map_builder.lua'.
[cartographer_node-1] I0527 01:26:40.000000 17428 configuration_file_resolver.cc:41] Found '/home/intel/robot_sdk/sdk_ws/device_ws/install/cartographer/share/cartographer/configuration_files/pose_graph.lua' for 'pose_graph.lua'.
[cartographer_node-1] I0527 01:26:40.000000 17428 configuration_file_resolver.cc:41] Found '/home/intel/robot_sdk/sdk_ws/device_ws/install/cartographer/share/cartographer/configuration_files/pose_graph.lua' for 'pose_graph.lua'.
[cartographer_node-1] I0527 01:26:40.000000 17428 configuration_file_resolver.cc:41] Found '/home/intel/robot_sdk/sdk_ws/device_ws/install/cartographer/share/cartographer/configuration_files/trajectory_builder.lua' for 'trajectory_builder.lua'.
[cartographer_node-1] I0527 01:26:40.000000 17428 configuration_file_resolver.cc:41] Found '/home/intel/robot_sdk/sdk_ws/device_ws/install/cartographer/share/cartographer/configuration_files/trajectory_builder.lua' for 'trajectory_builder.lua'.
[cartographer_node-1] I0527 01:26:40.000000 17428 configuration_file_resolver.cc:41] Found '/home/intel/robot_sdk/sdk_ws/device_ws/install/cartographer/share/cartographer/configuration_files/trajectory_builder_2d.lua' for 'trajectory_builder_2d.lua'.
[cartographer_node-1] I0527 01:26:40.000000 17428 configuration_file_resolver.cc:41] Found '/home/intel/robot_sdk/sdk_ws/device_ws/install/cartographer/share/cartographer/configuration_files/trajectory_builder_2d.lua' for 'trajectory_builder_2d.lua'.
[cartographer_node-1] I0527 01:26:40.000000 17428 configuration_file_resolver.cc:41] Found '/home/intel/robot_sdk/sdk_ws/device_ws/install/cartographer/share/cartographer/configuration_files/trajectory_builder_3d.lua' for 'trajectory_builder_3d.lua'.
[cartographer_node-1] I0527 01:26:40.000000 17428 configuration_file_resolver.cc:41] Found '/home/intel/robot_sdk/sdk_ws/device_ws/install/cartographer/share/cartographer/configuration_files/trajectory_builder_3d.lua' for 'trajectory_builder_3d.lua'.
[cartographer_node-1] [WARN] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[cartographer_node-1] I0527 01:26:40.000000 17428 submap_2d.cc:187] Added submap 1
[cartographer_node-1] I0527 01:26:40.000000 17428 map_builder_bridge.cc:132] Added trajectory with ID '0'.
[rviz2-3] [INFO] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-3] [INFO] [rviz2]: OpenGl version: 3 (GLSL 1.3)
[rviz2-3] [WARN] [rviz2]: Could not find folder /opt/robot_sdk/core/rviz_rendering_tests/share/rviz_rendering_tests/ogre_media_resources/scripts
[rviz2-3] [WARN] [rviz2]: Could not find folder /opt/robot_sdk/core/rviz_rendering_tests/share/rviz_rendering_tests/ogre_media_resources/meshes
[rviz2-3] [INFO] [rviz2]: Stereo is NOT SUPPORTED
[occupancy_grid_node-2] [WARN] [occupancy_grid_node]: submap_slices and last_frame_id is empty
[occupancy_grid_node-2] [WARN] [occupancy_grid_node]: submap_slices and last_frame_id is empty
[occupancy_grid_node-2] [WARN] [occupancy_grid_node]: submap_slices and last_frame_id is empty
[occupancy_grid_node-2] [WARN] [occupancy_grid_node]: submap_slices and last_frame_id is empty
[occupancy_grid_node-2] [WARN] [occupancy_grid_node]: submap_slices and last_frame_id is empty
[occupancy_grid_node-2] [WARN] [occupancy_grid_node]: submap_slices and last_frame_id is empty
[occupancy_grid_node-2] [WARN] [occupancy_grid_node]: submap_slices and last_frame_id is empty
[occupancy_grid_node-2] [WARN] [occupancy_grid_node]: submap_slices and last_frame_id is empty
[occupancy_grid_node-2] [WARN] [occupancy_grid_node]: submap_slices and last_frame_id is empty
[occupancy_grid_node-2] [WARN] [occupancy_grid_node]: submap_slices and last_frame_id is empty
[occupancy_grid_node-2] [WARN] [occupancy_grid_node]: submap_slices and last_frame_id is empty
[occupancy_grid_node-2] [WARN] [occupancy_grid_node]: submap_slices and last_frame_id is empty
[occupancy_grid_node-2] [WARN] [occupancy_grid_node]: submap_slices and last_frame_id is empty

BTW, if not upgrade all ubuntu patch (no run step3), this issue disappear. Does anyone met the same issue before, would you please share some experience about how to fix or debug?

**Comment by rafaelhuang-intel** [comment]
I also report this issue to TB3 (https://github.com/ROBOTIS-GIT/turtlebot3/issues/431), but it's seems this issue may cause by MicroXRCEAgent,. 

I tested on ROS2 Crystal, and double checked on Dashing release, the test result are same.

**Comment by rafaelhuang-intel** [comment]
currently I used commit (TB3 version: 74ab7d5,
MicroXRCEAgent: version: a495c65faa964ddc068ac6e1249f17f5c9f92787) in my environment for build and test, if not upgrade all ubuntu patch (no run above step3), this issue disappear, so I think this issue may cause by Ubuntu patch conflict with MicroXRCEAgent.

**Comment by BorjaOuterelo** [comment]
Hi, @rafaelhuang-intel is this still an open issue?

**Comment by rafaelhuang-intel** [comment]
Hi , @BorjaOuterelo  after tested Dashing release (https://github.com/ROBOTIS-GIT/turtlebot3/issues/431), all workable, so I will close this issue.
